CREATE TABLE USER_ROLE(
role_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE APP_USER(
user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
username VARCHAR(250) UNIQUE NOT NULL,
password VARCHAR(250) NOT NULL,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL,
role_id INTEGER REFERENCES USER_ROLE(role_id)
);

CREATE TABLE STUDY_SET (
study_set_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(250) UNIQUE NOT NULL,
owner_id INTEGER REFERENCES APP_USER(user_id)
);

CREATE TABLE CATEGORY (
category_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE FLASHCARD (
flashcard_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
question VARCHAR(250) UNIQUE NOT NULL,
answer VARCHAR(250) NOT NULL,
category_id INTEGER REFERENCES CATEGORY(category_id)
);

CREATE TABLE STUDY_SET_CARD (
PRIMARY KEY(study_set_id, flashcard_id),
study_set_id INTEGER REFERENCES STUDY_SET(study_set_id),
flashcard_id INTEGER REFERENCES FLASHCARD(flashcard_id)
);
